name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pylint check
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')

    - name: Mypy check
      continue-on-error: true
      run: |
        mypy $(git ls-files '*.py')

    - name: Isort check
      continue-on-error: true
      run: |
        isort --check-only $(git ls-files '*.py')

    - name: Black check
      continue-on-error: true
      run: |
        black --check $(git ls-files '*.py')

    - name: Unittests check
      continue-on-error: true
      run: |
        echo "unittests stub"
